export default {
  cloudRoad: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.5,
    magic: 1,
  },
  desert: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0,
    magic: 0,
  },
  enchantedForest: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.6,
    magic: 0.25,
  },
  fairyForest: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.6,
    magic: 0.5,
  },
  fairyRealm: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.7,
    magic: 0.75,
  },
  forest: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.6,
    magic: 0,
  },
  grasslands: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.5,
    magic: 0,
  },
  hauntedBasement: {
    elevation: 0.4,
    temperature: 0.4,
    humidity: 0.6,
    magic: 0.5,
  },
  hauntedHouse: {
    elevation: 0.5,
    temperature: 0.4,
    humidity: 0.6,
    magic: 0.5,
  },
  heaven: {
    elevation: 1,
    temperature: 0.5,
    humidity: 0.5,
    magic: 1,
  },
  hell: {
    elevation: 0,
    temperature: 1,
    humidity: 0,
    magic: 1,
  },
  magicTower: {
    elevation: 0.75,
    temperature: 0.5,
    humidity: 0.5,
    magic: 0.75,
  },
  magmaCave: {
    elevation: 0.25,
    temperature: 1,
    humidity: 0,
    magic: 0,
  },
  starRoad: {
    elevation: 0.5,
    temperature: 0.5,
    humidity: 0.5,
    magic: 1,
  },
  steamCave: {
    elevation: 0,
    temperature: 1,
    humidity: 0.5,
    magic: -1,
  },
  tower: {
    elevation: 0.75,
    temperature: 1,
    humidity: 0.5,
    magic: 0,
  },
  tundra: {
    elevation: 0,
    temperature: 0.25,
    humidity: 0,
    magic: 0,
  },
  tunnel: {
    elevation: 0.4,
    temperature: 0.4,
    humidity: 0.6,
    magic: 0,
  },
};
